os: linux

dist: xenial

language: ruby

jobs:
  include:
    - stage: java unit tests
      language: java
      jdk:
        - oraclejdk11
      before_script:
        - cd server
      script:
        - mvn test
    - stage: react unit tests
      language: node_js
      node_js:
        - "stable"
      before_install:
        - cd client
      install:
        - yarn install
      script:
        - yarn test
    - stage: deploy
      before_install:
        - wget -qO- https://toolbelt.heroku.com/install.sh | sh
        - cd client
      install:
        - yarn install
      before_script:
        - yarn build
        - mkdir -p ../server/src/main/resources/public
        - cp -r build/* ../server/src/main/resources/public
        - cd ../server
      script:
        - mvn clean heroku:deploy
