os: linux

dist: xenial

language: ruby

jobs:
  include:
    - stage: java tests
      language: java
      jdk:
        - oraclejdk11

      before_script:
        - cd server

      script:
        - mvn test
        
    - stage: Angular tests
      language: node_js
      node_js:
        - "stable"
      
      addons:
        chrome: stable
      
      cache:
        directories:
          - ./node_modules

      before_install:
        - cd client

      install:
        - npm install
      script:
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

    - stage: deploy
      before_install:
        - cd client
      install:
        - npm install
      before_script:
        - npm run build --prod
        - mkdir -p ../server/src/main/resources/public
        - cp -r build/* ../server/src/main/resources/public
        - cd ../server
      script:
        - mvn clean heroku:deploy
