os: linux

dist: xenial

sudo: false

language: node_js
node_js:
  - "11"
  
cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: java tests
      language: java
      jdk:
        - oraclejdk11

      before_script:
        - cd server

      script:
        - mvn test
        
    - stage: angular tests
      language: node_js
      node_js:
        - "11"
      
      addons:
        chrome: stable

      before_install:
        - cd client

      install:
        - npm install
        
      script:
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

    - stage: deploy to Azure
    
      if: branch = master

      before_install:
        - cd client
        
      install:
        - npm install

      before_script:
        - npm run build --prod
        - mkdir -p ../server/src/main/resources/public
        - cp -r dist/client/* ../server/src/main/resources/public
        - cd ../server
        - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        - az login -u ${AZURE_WA_USERNAME} -p ${AZURE_WA_PASSWORD}
        
      script:
        - mvn clean package azure-webapp:deploy
