os: linux
jobs:
  include:
    - language: java
      java: oraclejdk8
      before_script:
        - cd server
      script:
        - mvn test
    
    - language: node_js
      node_js: "stable"
      before_script:
        - cd client
      script:
        - yarn install
        - yarn test